# todo: fix << parameters.go-version >> look into contexts

name: go-getter

on: [push]

env:
  TEST_RESULTS_PATH: /tmp/test-results
  # might have to use datadog metrics here  
  WIN_TEST_RESULTS: c:\Users\circleci\AppData\Local\Temp\test-results

jobs:

  linux-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
      fail-fast: true

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: mkdir test results path
        run: mkdir -p ${{env.TEST_RESULTS_PATH}}

      - name: go mod download
        run: go mod download

      - name: Setup go mod cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Check go fmt output because it does not report non-zero when there are fmt changes
      - name: check go fmt
        run: |
          go fmt ./...
          files=$(go fmt ./...)
            if [ -n "$files" ]; then
              echo "The following file(s) do not conform to go fmt:"
              echo "$files"
              exit 1
            fi

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.8.2
      
      - name: Run go tests 
        run: |
          PACKAGE_NAMES=$(go list ./...)
          echo "Running $(echo $PACKAGE_NAMES | wc -w) packages"
          echo $PACKAGE_NAMES
          gotestsum --format=short-verbose --junitfile $TEST_RESULTS_PATH/go-getter/gotestsum-report.xml -- -p 2 -cover -race -args -vet=on -coverprofile=linux_cov.part $PACKAGE_NAMES
      
      # Save coverage report parts
      - name: Upload and Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux test results
          path: linux_cov.part

  windows-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        goos: [windows]
      fail-fast: true
    
    steps:
      - name: run git config
        run: git config --global core.autocrlf false

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup go mod cache
        uses: actions/cache@v3
        with:
          path: |
            /go
            c:\Windows\system32\config\systemprofile\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: download go modules
        run: go mod download
          
      - name: install gotestsum
        run: go install gotest.tools/gotestsum@v1.8.2
      
      - name: run go tests
        shell: bash
        run: |
          PACKAGE_NAMES=$(go list ./...)
          echo "Running $(echo $PACKAGE_NAMES | wc -w) packages"
          echo $PACKAGE_NAMES
          gotestsum --format=short-verbose --junitfile $TEST_RESULTS_PATH/go-getter/gotestsum-report.xml -- -p 2 -cover -race -coverprofile=win_cov.part $PACKAGE_NAMES
      
      # Save coverage report parts
      - name: Upload and Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows test results
          path: win_cov.part
    