# todo: fix cmd context

name: go-tests

on: 
  workflow_call:
    inputs:
      cmd:
        description: 'the cmd needed'
        required: true
        type: string
      platform:
        description: 'the platform needed'
        required: true
        type: string
      govet:
        required: true
        type: string

env:
  TEST_RESULTS_PATH: /tmp/test-results

jobs:
  run-gotests:
    runs-on: ubuntu-latest
    steps: 
      - name: run go tests
        run: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            echo "Running $(echo $PACKAGE_NAMES | wc -w) packages"
            echo $PACKAGE_NAMES
            << parameters.cmd >> --format=short-verbose --junitfile $TEST_RESULTS_PATH/go-getter/gotestsum-report.xml -- -p 2 -cover -race -vet=<< parameters.govet >> -coverprofile=<< parameters.platform >>_cov_$CIRCLE_NODE_INDEX.part $PACKAGE_NAMES